version: '3.8'
services:
  frontend:
    image: frontend:latest
    deploy:
      mode: global
    ports:
      - "80:80"
    command: uwsgi --ini /var/app/flask/frontend/uwsgi.ini
    volumes:
      - /var/app/flask/frontend:/var/app/flask/frontend
  backend:
    image: backend:latest
    deploy:
      mode: global
    ports:
      - "5000:5000"
    command: uwsgi --ini /var/app/flask/frontend/uwsgi.ini
    volumes:
      - /var/app/flask/backend:/var/app/flask/backend
