version: "3.8"
services:
  nginx:
    image: mynginx:latest
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "80:80"
      - "5050:5050"
    deploy:
      mode: global
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.nginx.service
  frontend:
    image: frontend:latest
    environment:
      - TZ=Asia/Tokyo
      - SESSION_ENCRYPTION_KEY=bGFuZHdhcnJpb3I=
    deploy:
      mode: global
    ports:
      - "8080:8080"
    command: uwsgi --ini /var/app/flask/frontend/uwsgi.ini
    volumes:
      - /var/app/flask/frontend:/var/app/flask/frontend
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.frontend.service
  backend:
    image: backend:latest
    environment:
      - TZ=Asia/Tokyo
    deploy:
      mode: global
    ports:
      - "5000:5000"
    command: uwsgi --ini /var/app/flask/backend/uwsgi.ini
    volumes:
      - /var/app/flask/backend:/var/app/flask/backend
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.backend.service
  batch:
    image: batch:latest
    environment:
      - TZ=Asia/Tokyo
    deploy:
      mode: global
    volumes:
      - /var/app/batch:/var/app/batch
    stdin_open: true
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.batch.service
  fluentd:
    image: myfluentd
    volumes:
      - /var/log/fluent:/var/log/fluent
    command:
      - fluentd
      - -c
      - /fluentd/etc/fluent.yml
    ports:
      - "24224:24224"
