CREATE USER IF NOT EXISTS myaccount@'%' identified BY 'myaccount';
CREATE USER IF NOT EXISTS myaccount@localhost identified BY 'myaccount';
GRANT ALL PRIVILEGES ON *.* TO myaccount@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO myaccount@localhost WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS mst_user (
  user_id VARCHAR (32) NOT NULL,
  user_name VARCHAR (100) NOT NULL,
  user_name_kana VARCHAR (100) NOT NULL,
  email VARCHAR (150) NOT NULL,
  gender VARCHAR (10) NOT NULL,
  age INT (11) NOT NULL,
  birth_day DATE NOT NULL,
  blood_type VARCHAR (10) NOT NULL,
  prefecture VARCHAR (10) NOT NULL,
  curry VARCHAR (100) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id)
)
;

INSERT IGNORE INTO mst_user VALUES 
  ('yanagisawa_naoto', '柳沢 直人', 'やなぎさわ なおと', 'yanagisawa_naoto@example.com', '男', 49, '1974/6/24', 'A型', '沖縄県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kumai_keita', '熊井 慶太', 'くまい けいた', 'kumai_keita@example.com', '男', 43, '1980/7/6', 'A型', '群馬県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('komine_youko', '小峰 陽子', 'こみね ようこ', 'komine_youko@example.com', '女', 25, '1998/10/9', 'A型', '山形県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('kawamoto_takashi', '川本 隆', 'かわもと たかし', 'kawamoto_takashi@example.com', '男', 36, '1987/7/12', 'O型', '新潟県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('kubo_masahiko', '久保 雅彦', 'くぼ まさひこ', 'kubo_masahiko@example.com', '男', 46, '1977/12/10', 'AB型', '愛知県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('konndou_mitsuhiro', '近藤 光博', 'こんどう みつひろ', 'konndou_mitsuhiro@example.com', '男', 43, '1980/8/22', 'A型', '東京都', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('oosaki_sachie', '大崎 沙知絵', 'おおさき さちえ', 'oosaki_sachie@example.com', '女', 22, '2001/5/20', 'A型', '岐阜県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('sugimura_takashi', '杉村 崇史', 'すぎむら たかし', 'sugimura_takashi@example.com', '男', 23, '2001/1/1', 'O型', '群馬県', '別盛り・別口派', DEFAULT, DEFAULT)
, ('kagawa_hiroyuki', '香川 博之', 'かがわ ひろゆき', 'kagawa_hiroyuki@example.com', '男', 38, '1985/11/4', 'A型', '茨城県', '左ルー・ナン派', DEFAULT, DEFAULT)
, ('miyashita_tatsuya', '宮下 竜也', 'みやした たつや', 'miyashita_tatsuya@example.com', '男', 55, '1968/7/18', 'A型', '福井県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('ishigaki_mamoru', '石垣 守', 'いしがき まもる', 'ishigaki_mamoru@example.com', '男', 35, '1988/6/20', 'A型', '福島県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('matsuzawa_koutarou', '松沢 浩太郎', 'まつざわ こうたろう', 'matsuzawa_koutarou@example.com', '男', 57, '1966/8/12', 'B型', '大阪府', '奥ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('kasuga_sachiko', '春日 幸子', 'かすが さちこ', 'kasuga_sachiko@example.com', '女', 25, '1998/5/15', 'B型', '愛知県', '左ルー・別口派', DEFAULT, DEFAULT)
, ('wakasugi_tatsuya', '若杉 竜也', 'わかすぎ たつや', 'wakasugi_tatsuya@example.com', '男', 34, '1989/8/14', 'B型', '和歌山県', '右ルー・別口派', DEFAULT, DEFAULT)
, ('aoyama_ai', '青山 愛', 'あおやま あい', 'aoyama_ai@example.com', '女', 32, '1991/8/29', 'A型', '大阪府', '左ルー・別口派', DEFAULT, DEFAULT)
, ('noro_yuu', '野呂 優', 'のろ ゆう', 'noro_yuu@example.com', '女', 31, '1992/5/24', 'A型', '東京都', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('yoshizawa_ann', '吉沢 杏', 'よしざわ あん', 'yoshizawa_ann@example.com', '女', 21, '2003/4/21', 'B型', '千葉県', '別盛り・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('yoshimoto_shunsuke', '吉本 俊介', 'よしもと しゅんすけ', 'yoshimoto_shunsuke@example.com', '男', 33, '1990/6/28', 'B型', '福岡県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('nakashima_sora', '中島 そら', 'なかしま そら', 'nakashima_sora@example.com', '女', 53, '1971/3/2', 'B型', '静岡県', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('fujioka_kazuki', '藤岡 一輝', 'ふじおか かずき', 'fujioka_kazuki@example.com', '男', 51, '1972/9/21', 'A型', '広島県', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('kojima_kaoru', '児島 薫', 'こじま かおる', 'kojima_kaoru@example.com', '女', 35, '1988/9/2', 'A型', '京都府', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('aibu_kogan', '相武 小雁', 'あいぶ こがん', 'aibu_kogan@example.com', '男', 29, '1994/6/17', 'B型', '富山県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('asakura_saki', '朝倉 咲', 'あさくら さき', 'asakura_saki@example.com', '女', 23, '2000/8/15', 'A型', '長崎県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('fukunaga_mahiru', '福永 まひる', 'ふくなが まひる', 'fukunaga_mahiru@example.com', '女', 36, '1987/9/6', 'O型', '静岡県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('yamada_hitori', '山田 ひとり', 'やまだ ひとり', 'yamada_hitori@example.com', '男', 45, '1978/5/21', 'A型', '埼玉県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('takaya_sousuke', '高谷 蒼甫', 'たかや そうすけ', 'takaya_sousuke@example.com', '男', 55, '1969/3/9', 'A型', '静岡県', '別盛り・せき止め派', DEFAULT, DEFAULT)
, ('takami_sora', '高見 そら', 'たかみ そら', 'takami_sora@example.com', '女', 45, '1979/1/10', 'B型', '福岡県', '左ルー・別口派', DEFAULT, DEFAULT)
, ('kurita_saki', '栗田 早紀', 'くりた さき', 'kurita_saki@example.com', '女', 38, '1985/6/30', 'A型', '青森県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('odajima_yuuichi', '小田島 祐一', 'おだじま ゆういち', 'odajima_yuuichi@example.com', '男', 55, '1968/9/25', 'O型', '茨城県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('miki_takeo', '美木 丈雄', 'みき たけお', 'miki_takeo@example.com', '男', 27, '1996/5/2', 'B型', '大阪府', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('miyano_tetsuji', '宮野 鉄二', 'みやの てつじ', 'miyano_tetsuji@example.com', '男', 44, '1980/2/21', 'A型', '新潟県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('ninomiya_hikaru', '二宮 光', 'にのみや ひかる', 'ninomiya_hikaru@example.com', '女', 54, '1969/12/28', 'A型', '栃木県', '左ルー・別口派', DEFAULT, DEFAULT)
, ('kannbara_mei', '神原 芽以', 'かんばら めい', 'kannbara_mei@example.com', '女', 44, '1979/8/3', 'O型', '熊本県', 'ぶっかけ・ナン派', DEFAULT, DEFAULT)
, ('abe_masami', '阿部 まさみ', 'あべ まさみ', 'abe_masami@example.com', '女', 58, '1965/6/8', 'AB型', '群馬県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('chiba_maho', '千葉 真帆', 'ちば まほ', 'chiba_maho@example.com', '女', 47, '1976/8/5', 'B型', '大阪府', '右ルー・別口派', DEFAULT, DEFAULT)
, ('konno_asami', '紺野 あさみ', 'こんの あさみ', 'konno_asami@example.com', '女', 56, '1967/6/11', 'AB型', '滋賀県', '奥ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('toyoshima_keisuke', '豊島 啓介', 'とよしま けいすけ', 'toyoshima_keisuke@example.com', '男', 35, '1989/2/10', 'B型', '広島県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('shouji_shingo', '少路 信吾', 'しょうじ しんご', 'shouji_shingo@example.com', '男', 34, '1989/9/19', 'AB型', '茨城県', '別盛り・せき止め派', DEFAULT, DEFAULT)
, ('matsuda_shidou', '松田 獅童', 'まつだ しどう', 'matsuda_shidou@example.com', '男', 48, '1975/8/5', 'O型', '和歌山県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('sawai_kazuya', '沢井 一哉', 'さわい かずや', 'sawai_kazuya@example.com', '男', 37, '1986/7/19', 'A型', '栃木県', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('matsuoka_atsushi', '松岡 惇', 'まつおか あつし', 'matsuoka_atsushi@example.com', '男', 32, '1991/7/16', 'O型', '広島県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('sudou_shunji', '須藤 俊二', 'すどう しゅんじ', 'sudou_shunji@example.com', '男', 42, '1982/3/3', 'B型', '和歌山県', 'ぶっかけ・ナン派', DEFAULT, DEFAULT)
, ('satou_arata', '佐藤 新太', 'さとう あらた', 'satou_arata@example.com', '男', 51, '1972/9/12', 'B型', '茨城県', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('kurata_kikuo', '倉田 菊生', 'くらた きくお', 'kurata_kikuo@example.com', '男', 55, '1968/10/14', 'A型', '北海道', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('oohara_hidetsugu', '大原 英嗣', 'おおはら ひでつぐ', 'oohara_hidetsugu@example.com', '男', 36, '1987/12/16', 'O型', '東京都', '手前ルー・別口派', DEFAULT, DEFAULT)
, ('ninomiya_toshie', '二宮 季衣', 'にのみや としえ', 'ninomiya_toshie@example.com', '女', 38, '1985/10/24', 'A型', '福岡県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('mishima_mayuko', '三島 真悠子', 'みしま まゆこ', 'mishima_mayuko@example.com', '女', 36, '1987/6/6', 'O型', '愛知県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('komatsu_seiji', '小松 誠治', 'こまつ せいじ', 'komatsu_seiji@example.com', '男', 31, '1993/1/24', 'O型', '滋賀県', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('fukuchi_masayuki', '福地 雅之', 'ふくち まさゆき', 'fukuchi_masayuki@example.com', '男', 38, '1985/10/10', 'O型', '長野県', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('ogawa_koutarou', '小川 孝太郎', 'おがわ こうたろう', 'ogawa_koutarou@example.com', '男', 31, '1993/1/17', 'B型', '神奈川県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('waizumi_nobuhiko', '和泉 ノブヒコ', 'わいずみ のぶひこ', 'waizumi_nobuhiko@example.com', '男', 56, '1967/9/21', 'A型', '北海道', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('kubota_erika', '久保田 恵梨香', 'くぼた えりか', 'kubota_erika@example.com', '女', 48, '1976/3/10', 'O型', '静岡県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('tamada_saya', '玉田 沙耶', 'たまだ さや', 'tamada_saya@example.com', '女', 56, '1967/5/19', 'O型', '大分県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('kozeki_noriko', '小関 倫子', 'こぜき のりこ', 'kozeki_noriko@example.com', '女', 43, '1980/8/1', 'A型', '東京都', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('sone_masaya', '曽根 将也', 'そね まさや', 'sone_masaya@example.com', '男', 57, '1967/4/19', 'A型', '沖縄県', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('ishida_atsushi', '石田 惇', 'いしだ あつし', 'ishida_atsushi@example.com', '男', 35, '1988/7/10', 'O型', '宮城県', '手前ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('watanabe_reina', '渡辺 怜奈', 'わたなべ れいな', 'watanabe_reina@example.com', '女', 46, '1978/1/18', 'AB型', '茨城県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('sawada_yuu', '沢田 優', 'さわだ ゆう', 'sawada_yuu@example.com', '女', 37, '1986/9/18', 'A型', '富山県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('machida_shinichi', '町田 真一', 'まちだ しんいち', 'machida_shinichi@example.com', '男', 43, '1980/11/22', 'A型', '千葉県', '奥ルー・ナン派', DEFAULT, DEFAULT)
, ('matsushita_you', '松下 窈', 'まつした よう', 'matsushita_you@example.com', '女', 31, '1993/2/14', 'B型', '東京都', 'ぶっかけ・ナン派', DEFAULT, DEFAULT)
, ('tomisawa_megumi', '富沢 めぐみ', 'とみさわ めぐみ', 'tomisawa_megumi@example.com', '女', 34, '1989/9/14', 'O型', '埼玉県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('yoshikawa_mamoru', '吉川 守', 'よしかわ まもる', 'yoshikawa_mamoru@example.com', '男', 60, '1963/6/18', 'B型', '東京都', '別盛り・ルー攻め派', DEFAULT, DEFAULT)
, ('segawa_chise', '瀬川 知世', 'せがわ ちせ', 'segawa_chise@example.com', '女', 27, '1997/1/7', 'A型', '宮崎県', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('obata_mitsuru', '小畑 満', 'おばた みつる', 'obata_mitsuru@example.com', '男', 59, '1964/7/24', 'A型', '兵庫県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('shibata_hana', '柴田 花', 'しばた はな', 'shibata_hana@example.com', '女', 41, '1983/3/22', 'B型', '兵庫県', '奥ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('akiyama_karoku', '秋山 花緑', 'あきやま かろく', 'akiyama_karoku@example.com', '男', 44, '1979/7/9', 'A型', '大阪府', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('hamada_rio', '浜田 莉緒', 'はまだ りお', 'hamada_rio@example.com', '女', 39, '1984/7/25', 'B型', '大分県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('fujisawa_sayaka', '藤沢 さやか', 'ふじさわ さやか', 'fujisawa_sayaka@example.com', '女', 23, '2000/9/26', 'A型', '神奈川県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('arita_shouta', '有田 翔太', 'ありた しょうた', 'arita_shouta@example.com', '男', 50, '1973/5/15', 'O型', '滋賀県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('shimura_sayuri', '志村 小百合', 'しむら さゆり', 'shimura_sayuri@example.com', '女', 59, '1964/12/31', 'O型', '神奈川県', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('ohara_juri', '小原 樹里', 'おはら じゅり', 'ohara_juri@example.com', '女', 43, '1980/11/30', 'B型', '北海道', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('miyake_megumi', '三宅 めぐみ', 'みやけ めぐみ', 'miyake_megumi@example.com', '女', 30, '1994/3/4', 'O型', '静岡県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('ishizaki_satoshi', '石崎 聡', 'いしざき さとし', 'ishizaki_satoshi@example.com', '男', 51, '1973/2/22', 'O型', '神奈川県', '左ルー・ナン派', DEFAULT, DEFAULT)
, ('sudou_asahi', '首藤 朝陽', 'すどう あさひ', 'sudou_asahi@example.com', '女', 32, '1991/6/15', 'O型', '奈良県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('sugimura_miyuki', '杉村 みゆき', 'すぎむら みゆき', 'sugimura_miyuki@example.com', '女', 55, '1968/7/30', 'B型', '富山県', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('tsushima_reiko', '対馬 礼子', 'つしま れいこ', 'tsushima_reiko@example.com', '女', 39, '1984/7/11', 'A型', '兵庫県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('tsuruta_miho', '鶴田 美帆', 'つるた みほ', 'tsuruta_miho@example.com', '女', 39, '1984/6/4', 'AB型', '静岡県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('odajima_aki', '小田島 亜希', 'おだじま あき', 'odajima_aki@example.com', '女', 47, '1976/12/4', 'A型', '長野県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('takenaka_erika', '竹中 恵梨香', 'たけなか えりか', 'takenaka_erika@example.com', '女', 22, '2001/5/12', 'A型', '埼玉県', '左ルー・ナン派', DEFAULT, DEFAULT)
, ('haga_misako', '芳賀 美佐子', 'はが みさこ', 'haga_misako@example.com', '女', 36, '1987/6/4', 'A型', '広島県', '手前ルー・せき止め派', DEFAULT, DEFAULT)
, ('panzetta_nagatoshi', 'パンツェッタ 長利', 'ぱんつぇった ながとし', 'panzetta_nagatoshi@example.com', '男', 52, '1972/2/9', 'O型', '東京都', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('akasaka_shun', '赤坂 瞬', 'あかさか しゅん', 'akasaka_shun@example.com', '男', 38, '1985/7/12', 'AB型', '東京都', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('matsumoto_nanami', '松元 菜々美', 'まつもと ななみ', 'matsumoto_nanami@example.com', '女', 33, '1991/3/18', 'A型', '栃木県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('narumi_yuuta', '成海 勇太', 'なるみ ゆうた', 'narumi_yuuta@example.com', '男', 36, '1988/2/28', 'A型', '北海道', '奥ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kohori_ouga', '小堀 碧海', 'こほり おうが', 'kohori_ouga@example.com', '男', 37, '1986/11/22', 'O型', '東京都', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('yoneda_yoshino', '米田 佳乃', 'よねだ よしの', 'yoneda_yoshino@example.com', '女', 46, '1977/5/28', 'O型', '三重県', '奥ルー・ナン派', DEFAULT, DEFAULT)
, ('oouchi_sachiko', '大内 幸子', 'おおうち さちこ', 'oouchi_sachiko@example.com', '女', 46, '1977/7/7', 'B型', '岩手県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('nozaki_masaya', '野崎 将也', 'のざき まさや', 'nozaki_masaya@example.com', '男', 27, '1996/5/6', 'A型', '宮城県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('akimoto_yuuichi', '秋元 優一', 'あきもと ゆういち', 'akimoto_yuuichi@example.com', '男', 48, '1975/9/15', 'O型', '香川県', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('nishimura_subaru', '西村 昴', 'にしむら すばる', 'nishimura_subaru@example.com', '男', 45, '1978/12/4', 'B型', '三重県', '奥ルー・せき止め派', DEFAULT, DEFAULT)
, ('someya_rokurou', '染谷 禄郎', 'そめや ろくろう', 'someya_rokurou@example.com', '男', 23, '2000/5/1', 'O型', '大阪府', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('kubota_maho', '久保田 真帆', 'くぼた まほ', 'kubota_maho@example.com', '女', 43, '1981/3/30', 'A型', '神奈川県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('kawabata_kenichi', '川端 ケンイチ', 'かわばた けんいち', 'kawabata_kenichi@example.com', '男', 21, '2002/6/8', 'A型', '茨城県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('teranishi_sanma', '寺西 さんま', 'てらにし さんま', 'teranishi_sanma@example.com', '男', 40, '1983/7/4', 'A型', '大阪府', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('sawada_yuuji', '沢田 裕司', 'さわだ ゆうじ', 'sawada_yuuji@example.com', '男', 49, '1974/8/11', 'A型', '東京都', '手前ルー・せき止め派', DEFAULT, DEFAULT)
, ('ikegami_waka', '池上 和香', 'いけがみ わか', 'ikegami_waka@example.com', '女', 41, '1983/4/9', 'A型', '大阪府', '奥ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('ban_takeo', '伴 丈雄', 'ばん たけお', 'ban_takeo@example.com', '男', 23, '2001/4/2', 'A型', '富山県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('takeuchi_masahiko', '竹内 雅彦', 'たけうち まさひこ', 'takeuchi_masahiko@example.com', '男', 42, '1981/8/7', 'O型', '香川県', '手前ルー・ナン派', DEFAULT, DEFAULT)
, ('shiotani_toshiaki', '塩谷 寿明', 'しおたに としあき', 'shiotani_toshiaki@example.com', '男', 50, '1973/8/24', 'O型', '富山県', '左ルー・別口派', DEFAULT, DEFAULT)
, ('hada_youko', '羽田 陽子', 'はだ ようこ', 'hada_youko@example.com', '女', 29, '1994/11/27', 'A型', '兵庫県', '左ルー・ナン派', DEFAULT, DEFAULT)
, ('murase_masayoshi', '村瀬 正義', 'むらせ まさよし', 'murase_masayoshi@example.com', '男', 38, '1986/1/30', 'O型', '愛知県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('nakamura_erika', '仲村 恵梨香', 'なかむら えりか', 'nakamura_erika@example.com', '女', 56, '1968/2/24', 'A型', '大阪府', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('takeuchi_keiko', '武内 景子', 'たけうち けいこ', 'takeuchi_keiko@example.com', '女', 49, '1975/4/6', 'A型', '埼玉県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('umezawa_ruria', '梅沢 瑠璃亜', 'うめざわ るりあ', 'umezawa_ruria@example.com', '女', 34, '1990/3/30', 'B型', '福岡県', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('hidaka_saya', '日高 沙耶', 'ひだか さや', 'hidaka_saya@example.com', '女', 47, '1977/1/30', 'A型', '奈良県', '手前ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('tsujimoto_youko', '辻本 陽子', 'つじもと ようこ', 'tsujimoto_youko@example.com', '女', 37, '1987/3/4', 'B型', '香川県', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('nagasawa_rina', '長澤 里奈', 'ながさわ りな', 'nagasawa_rina@example.com', '女', 39, '1985/4/17', 'O型', '大阪府', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('yanagiya_shinnosuke', '柳家 慎之介', 'やなぎや しんのすけ', 'yanagiya_shinnosuke@example.com', '男', 45, '1978/6/7', 'A型', '福岡県', '手前ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('kumasawa_nanase', '熊沢 七世', 'くまさわ ななせ', 'kumasawa_nanase@example.com', '女', 59, '1965/1/3', 'B型', '愛知県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('minami_hanako', '南 華子', 'みなみ はなこ', 'minami_hanako@example.com', '女', 49, '1975/1/2', 'B型', '東京都', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('honjo_eiichi', '本上 栄一', 'ほんじょう えいいち', 'honjo_eiichi@example.com', '男', 43, '1980/8/25', 'O型', '埼玉県', '奥ルー・せき止め派', DEFAULT, DEFAULT)
, ('nishi_kaoru', '西 薫', 'にし かおる', 'nishi_kaoru@example.com', '女', 40, '1984/4/1', 'O型', '兵庫県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('hayami_takeshi', '早美 丈史', 'はやみ たけし', 'hayami_takeshi@example.com', '男', 47, '1976/4/30', 'O型', '山口県', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('machida_tomoka', '町田 智花', 'まちだ ともか', 'machida_tomoka@example.com', '女', 46, '1977/4/29', 'A型', '茨城県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kawamoto_tatsuya', '川本 竜也', 'かわもと たつや', 'kawamoto_tatsuya@example.com', '男', 43, '1981/2/16', 'B型', '神奈川県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('tsuruoka_shou', '鶴岡 翔', 'つるおか しょう', 'tsuruoka_shou@example.com', '男', 42, '1981/6/2', 'A型', '岩手県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('matsuda_fumiya', '松田 フミヤ', 'まつだ ふみや', 'matsuda_fumiya@example.com', '男', 35, '1988/7/21', 'O型', '和歌山県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('yamaguchi_reina', '山口 怜奈', 'やまぐち れいな', 'yamaguchi_reina@example.com', '女', 31, '1993/3/5', 'O型', '埼玉県', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('yonezawa_riko', '米沢 璃子', 'よねざわ りこ', 'yonezawa_riko@example.com', '女', 31, '1992/7/30', 'A型', '長野県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('umezawa_teppei', '梅沢 哲平', 'うめざわ てっぺい', 'umezawa_teppei@example.com', '男', 50, '1973/6/6', 'B型', '大阪府', '奥ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('ichihara_manami', '市原 まなみ', 'いちはら まなみ', 'ichihara_manami@example.com', '女', 53, '1971/1/29', 'A型', '東京都', '奥ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('morikawa_kousuke', '森川 浩介', 'もりかわ こうすけ', 'morikawa_kousuke@example.com', '男', 30, '1993/12/18', 'AB型', '愛知県', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('morishita_masahiko', '森下 雅彦', 'もりした まさひこ', 'morishita_masahiko@example.com', '男', 27, '1996/5/25', 'B型', '鹿児島県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('honjo_ryuunosuke', '本上 隆之介', 'ほんじょう りゅうのすけ', 'honjo_ryuunosuke@example.com', '男', 40, '1984/2/4', 'B型', '神奈川県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('wakatsuki_saki', '若槻 咲', 'わかつき さき', 'wakatsuki_saki@example.com', '女', 47, '1977/1/2', 'AB型', '京都府', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('honnda_kaoru', '本田 薫', 'ほんだ かおる', 'honnda_kaoru@example.com', '女', 51, '1972/8/4', 'A型', '千葉県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('nakaoka_haruomi', '中岡 晴臣', 'なかおか はるおみ', 'nakaoka_haruomi@example.com', '男', 55, '1968/9/29', 'O型', '愛知県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kotani_teruo', '小谷 照生', 'こたに てるお', 'kotani_teruo@example.com', '男', 21, '2002/7/14', 'B型', '東京都', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('tagawa_yuu', '田川 優', 'たがわ ゆう', 'tagawa_yuu@example.com', '女', 20, '2003/12/18', 'B型', '福岡県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('kokubo_toshie', '小久保 季衣', 'こくぼ としえ', 'kokubo_toshie@example.com', '女', 28, '1995/12/14', 'AB型', '三重県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('moriya_youko', '守屋 陽子', 'もりや ようこ', 'moriya_youko@example.com', '女', 50, '1973/9/12', 'O型', '京都府', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('yoshinaga_takashi', '吉永 崇史', 'よしなが たかし', 'yoshinaga_takashi@example.com', '男', 33, '1990/10/23', 'A型', '北海道', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('tsukamoto_yuu', '塚本 優', 'つかもと ゆう', 'tsukamoto_yuu@example.com', '女', 22, '2001/11/6', 'A型', '愛知県', '手前ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('inada_manami', '稲田 まなみ', 'いなだ まなみ', 'inada_manami@example.com', '女', 34, '1989/6/9', 'O型', '愛知県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('konno_nobuhiko', '紺野 ノブヒコ', 'こんの のぶひこ', 'konno_nobuhiko@example.com', '男', 22, '2001/9/21', 'AB型', '山口県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('suga_keiko', '須賀 景子', 'すが けいこ', 'suga_keiko@example.com', '女', 51, '1973/3/23', 'B型', '大阪府', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('sakamoto_megumi', '坂元 恵美', 'さかもと めぐみ', 'sakamoto_megumi@example.com', '女', 25, '1998/7/26', 'A型', '千葉県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('tomita_hiro', '富田 ヒロ', 'とみた ひろ', 'tomita_hiro@example.com', '男', 32, '1992/2/13', 'AB型', '兵庫県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('murase_hidetsugu', '村瀬 英嗣', 'むらせ ひでつぐ', 'murase_hidetsugu@example.com', '男', 22, '2001/6/15', 'A型', '北海道', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('shikatebukuro_kaoru', '鹿手袋 薫', 'しかてぶくろ かおる', 'shikatebukuro_kaoru@example.com', '男', 48, '1975/11/11', 'O型', '福岡県', '手前ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('tadokoro_masashi', '田所 まさし', 'たどころ まさし', 'tadokoro_masashi@example.com', '男', 51, '1972/6/28', 'O型', '新潟県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('mizoguchi_takashi', '溝口 隆', 'みぞぐち たかし', 'mizoguchi_takashi@example.com', '男', 48, '1976/2/16', 'O型', '北海道', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('yoshii_miwako', '吉井 美和子', 'よしい みわこ', 'yoshii_miwako@example.com', '女', 25, '1998/6/22', 'B型', '千葉県', '左ルー・別口派', DEFAULT, DEFAULT)
, ('takakura_hiro', '高倉 ヒロ', 'たかくら ひろ', 'takakura_hiro@example.com', '男', 33, '1991/1/14', 'B型', '奈良県', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('sugasawa_hana', '菅澤 花', 'すがさわ はな', 'sugasawa_hana@example.com', '女', 46, '1978/3/30', 'A型', '東京都', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kakei_kyouko', '筧 恭子', 'かけい きょうこ', 'kakei_kyouko@example.com', '女', 28, '1995/11/3', 'A型', '北海道', '奥ルー・別口派', DEFAULT, DEFAULT)
, ('ijuuin_tasuku', '伊集院 佑', 'いじゅういん たすく', 'ijuuin_tasuku@example.com', '男', 40, '1984/3/19', 'A型', '愛知県', '手前ルー・せき止め派', DEFAULT, DEFAULT)
, ('toda_sachie', '戸田 沙知絵', 'とだ さちえ', 'toda_sachie@example.com', '女', 38, '1986/2/4', 'A型', '静岡県', '左ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('sakamoto_yukiya', '坂本 有起哉', 'さかもと ゆきや', 'sakamoto_yukiya@example.com', '男', 51, '1972/8/23', 'AB型', '東京都', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('moriyama_meisa', '森山 メイサ', 'もりやま めいさ', 'moriyama_meisa@example.com', '女', 43, '1980/7/12', 'B型', '東京都', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('maekawa_saki', '前川 咲', 'まえかわ さき', 'maekawa_saki@example.com', '女', 22, '2001/5/26', 'A型', '滋賀県', '奥ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('tsugawa_saki', '津川 早紀', 'つがわ さき', 'tsugawa_saki@example.com', '女', 38, '1986/1/30', 'B型', '広島県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('nagasawa_hiromasa', '長沢 浩正', 'ながさわ ひろまさ', 'nagasawa_hiromasa@example.com', '男', 56, '1968/3/26', 'A型', '大阪府', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('kano_you', '狩野 洋', 'かの よう', 'kano_you@example.com', '男', 54, '1969/6/15', 'O型', '大分県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('hayami_erika', '早美 恵梨香', 'はやみ えりか', 'hayami_erika@example.com', '女', 30, '1993/7/28', 'O型', '埼玉県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('kawahara_yuu', '河原 優', 'かわはら ゆう', 'kawahara_yuu@example.com', '女', 44, '1980/1/16', 'B型', '福岡県', '奥ルー・せき止め派', DEFAULT, DEFAULT)
, ('banntou_sansei', '坂東 三省', 'ばんとう さんせい', 'banntou_sansei@example.com', '男', 24, '1999/11/26', 'A型', '岐阜県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('matsushima_chinatsu', '松島 千夏', 'まつしま ちなつ', 'matsushima_chinatsu@example.com', '女', 30, '1993/7/9', 'O型', '兵庫県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('oonishi_mia', '大西 みあ', 'おおにし みあ', 'oonishi_mia@example.com', '女', 49, '1974/4/25', 'O型', '秋田県', '右ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('masui_tooru', '増井 徹', 'ますい とおる', 'masui_tooru@example.com', '男', 27, '1996/10/16', 'O型', '東京都', 'ぶっかけ・別口派', DEFAULT, DEFAULT)
, ('asami_mantarou', '浅見 慢太郎', 'あさみ まんたろう', 'asami_mantarou@example.com', '男', 28, '1996/2/11', 'A型', '兵庫県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('nishikawa_megumi', '西川 めぐみ', 'にしかわ めぐみ', 'nishikawa_megumi@example.com', '女', 45, '1979/4/1', 'A型', '秋田県', '右ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('asou_nana', '麻生 那奈', 'あそう なな', 'asou_nana@example.com', '女', 22, '2001/7/4', 'A型', '熊本県', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('sotoyama_miki', '外山 みき', 'そとやま みき', 'sotoyama_miki@example.com', '女', 60, '1963/6/14', 'O型', '宮城県', '右ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('katsudi_hikaru', '勝地 ヒカル', 'かつぢ ひかる', 'katsudi_hikaru@example.com', '女', 31, '1993/3/19', 'O型', '大阪府', '右ルー・ナン派', DEFAULT, DEFAULT)
, ('katahira_nobuhiko', '片平 ノブヒコ', 'かたひら のぶひこ', 'katahira_nobuhiko@example.com', '男', 41, '1983/2/1', 'O型', '福岡県', '手前ルー・別口派', DEFAULT, DEFAULT)
, ('fujimoto_rio', '藤本 莉央', 'ふじもと りお', 'fujimoto_rio@example.com', '女', 49, '1974/9/27', 'A型', '奈良県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('minato_megumi', '湊 めぐみ', 'みなと めぐみ', 'minato_megumi@example.com', '女', 37, '1986/5/5', 'AB型', '群馬県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kusakabe_kadue', '日下部 一恵', 'くさかべ かづえ', 'kusakabe_kadue@example.com', '女', 29, '1995/1/2', 'A型', '兵庫県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('ooyama_ryousuke', '大山 良介', 'おおやま りょうすけ', 'ooyama_ryousuke@example.com', '男', 47, '1976/11/1', 'B型', '宮崎県', '奥ルー・ナン派', DEFAULT, DEFAULT)
, ('mizoguchi_kousuke', '溝口 浩介', 'みぞぐち こうすけ', 'mizoguchi_kousuke@example.com', '男', 47, '1976/5/27', 'O型', '埼玉県', '右ルー・せき止め派', DEFAULT, DEFAULT)
, ('nojima_yuu', '野島 由宇', 'のじま ゆう', 'nojima_yuu@example.com', '女', 38, '1985/6/30', 'B型', '福岡県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('iijima_kenji', '飯島 研二', 'いいじま けんじ', 'iijima_kenji@example.com', '男', 23, '2001/3/20', 'AB型', '北海道', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('yamagata_mahiru', '山形 まひる', 'やまがた まひる', 'yamagata_mahiru@example.com', '女', 35, '1988/7/11', 'A型', '群馬県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('morikawa_chiemi', '森川 ちえみ', 'もりかわ ちえみ', 'morikawa_chiemi@example.com', '女', 38, '1985/6/20', 'O型', '東京都', 'ぶっかけ・ナン派', DEFAULT, DEFAULT)
, ('kuribayashi_tarou', '栗林 太朗', 'くりばやし たろう', 'kuribayashi_tarou@example.com', '男', 23, '2000/6/24', 'A型', '和歌山県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('umino_reina', '海野 怜奈', 'うみの れいな', 'umino_reina@example.com', '女', 33, '1991/2/20', 'O型', '富山県', '奥ルー・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('yamagishi_haruka', '山岸 はるか', 'やまぎし はるか', 'yamagishi_haruka@example.com', '女', 28, '1996/1/20', 'O型', '北海道', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('iwata_hidetaka', '岩田 秀隆', 'いわた ひでたか', 'iwata_hidetaka@example.com', '男', 56, '1968/2/7', 'B型', '兵庫県', '奥ルー・ナン派', DEFAULT, DEFAULT)
, ('yamagami_hiro', '山上 ヒロ', 'やまがみ ひろ', 'yamagami_hiro@example.com', '男', 21, '2003/1/20', 'O型', '京都府', 'ぶっかけ・混ぜ混ぜ派', DEFAULT, DEFAULT)
, ('makita_kenji', '牧田 賢二', 'まきた けんじ', 'makita_kenji@example.com', '男', 57, '1966/9/14', 'AB型', '愛知県', '別盛り・せき止め派', DEFAULT, DEFAULT)
, ('ochi_kanji', '越智 完爾', 'おち かんじ', 'ochi_kanji@example.com', '男', 35, '1988/6/6', 'B型', '宮城県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('shinohara_fumiyo', '篠原 文世', 'しのはら ふみよ', 'shinohara_fumiyo@example.com', '女', 53, '1971/4/21', 'B型', '神奈川県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('kuroki_reina', '黒木 怜奈', 'くろき れいな', 'kuroki_reina@example.com', '女', 51, '1972/12/8', 'B型', '宮城県', '奥ルー・せき止め派', DEFAULT, DEFAULT)
, ('oda_somegorou', '小田 染五郎', 'おだ そめごろう', 'oda_somegorou@example.com', '男', 35, '1988/7/30', 'A型', '東京都', '左ルー・別口派', DEFAULT, DEFAULT)
, ('akagi_megumi', '赤木 めぐみ', 'あかぎ めぐみ', 'akagi_megumi@example.com', '女', 59, '1964/11/9', 'A型', '福岡県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('ooki_yutaka', '大木 豊', 'おおき ゆたか', 'ooki_yutaka@example.com', '男', 22, '2001/9/17', 'O型', '石川県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('hirokawa_nao', '広川 南朋', 'ひろかわ なお', 'hirokawa_nao@example.com', '女', 56, '1967/10/17', 'O型', '埼玉県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('yamamoto_saori', '山本 早織', 'やまもと さおり', 'yamamoto_saori@example.com', '女', 28, '1995/8/28', 'A型', '三重県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('tachibana_tasuku', '橘 佑', 'たちばな たすく', 'tachibana_tasuku@example.com', '男', 38, '1985/7/27', 'B型', '神奈川県', '奥ルー・せき止め派', DEFAULT, DEFAULT)
, ('murata_aya', '村田 彩', 'むらた あや', 'murata_aya@example.com', '女', 42, '1981/5/19', 'O型', '石川県', '手前ルー・せき止め派', DEFAULT, DEFAULT)
, ('hiraoka_nobuhiko', '平岡 ノブヒコ', 'ひらおか のぶひこ', 'hiraoka_nobuhiko@example.com', '男', 33, '1990/8/31', 'O型', '岡山県', '奥ルー・別口派', DEFAULT, DEFAULT)
, ('asanuma_ayame', '浅沼 綾女', 'あさぬま あやめ', 'asanuma_ayame@example.com', '女', 21, '2003/3/27', 'B型', '東京都', '奥ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('komuro_yuino', '小室 友以乃', 'こむろ ゆいの', 'komuro_yuino@example.com', '女', 56, '1967/9/28', 'O型', '大阪府', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('numata_chise', '沼田 知世', 'ぬまた ちせ', 'numata_chise@example.com', '女', 33, '1991/1/10', 'B型', '千葉県', '手前ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('matsumoto_yuu', '松本 優', 'まつもと ゆう', 'matsumoto_yuu@example.com', '男', 44, '1979/12/20', 'B型', '沖縄県', 'ぶっかけ・せき止め派', DEFAULT, DEFAULT)
, ('mishima_sayuri', '三島 さゆり', 'みしま さゆり', 'mishima_sayuri@example.com', '女', 47, '1976/8/15', 'O型', '岡山県', 'ぶっかけ・ルー攻め派', DEFAULT, DEFAULT)
, ('nakahara_reiko', '中原 礼子', 'なかはら れいこ', 'nakahara_reiko@example.com', '女', 60, '1963/11/18', 'AB型', '石川県', '左ルー・ルー攻め派', DEFAULT, DEFAULT)
, ('ishihara_sayuri', '石原 さゆり', 'いしはら さゆり', 'ishihara_sayuri@example.com', '女', 35, '1988/7/8', 'O型', '福岡県', '左ルー・せき止め派', DEFAULT, DEFAULT)
, ('oonuma_michiko', '大沼 美智子', 'おおぬま みちこ', 'oonuma_michiko@example.com', '女', 42, '1981/7/8', 'AB型', '徳島県', '右ルー・ルー攻め派', DEFAULT, DEFAULT)
;
